# Generated by Django 5.2.6 on 2026-05-17 02:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_productvariant_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
