# Generated by Django 5.2.6 on 2026-06-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
