# Generated by Django 5.2.6 on 2026-07-19 09:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
