# Generated by Django 5.2.6 on 2026-07-28 07:01

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_order_full_name_order_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='review_image')),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Review Gallery Image',
                'verbose_name_plural': 'Review Gallery Images',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
