# Generated by Django 5.2.6 on 2026-07-28 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_reviewgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewgallery',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Review image', 'verbose_name_plural': 'Review images'},
        ),
        migrations.RemoveField(
            model_name='reviewgallery',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='reviewgallery',
            name='customer_name',
        ),
    ]
