import { useEffect, useMemo, useState } from "react";
import { Images, Eye, EyeOff, Search, Trash2, Pencil, X, UploadCloud } from "lucide-react";
import toast from "react-hot-toast";
import DashboardLayout from "../layouts/DashboardLayout";
import { api } from "../api/axios";
function Stat({icon:Icon,label,value,tone}){return <div className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><div className="flex items-center gap-4"><span className={`grid h-11 w-11 place-items-center rounded-2xl ${tone}`}><Icon size={20}/></span><div><p className="text-xs text-gray-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div></div></div>}
export default function ReviewGallery({onLogout}){const [reviews,setReviews]=useState([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[filter,setFilter]=useState("all"),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[image,setImage]=useState(null),[preview,setPreview]=useState(""),[active,setActive]=useState(true),[order,setOrder]=useState(0);
 const load=async()=>{try{const r=await api.get("review-gallery/");setReviews(r.data||[])}catch{toast.error("Unable to load review gallery")}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const visible=useMemo(()=>reviews.filter(r=>(filter==="all"||String(r.is_active)===(filter==="active"?"true":"false"))&&String(r.id).includes(search)),[reviews,filter,search]);
 const showCreate=()=>{setEditing(null);setImage(null);setPreview("");setActive(true);setOrder(0);setOpen(true)};const showEdit=r=>{setEditing(r);setImage(null);setPreview(r.image_url||r.image||"");setActive(r.is_active);setOrder(r.display_order||0);setOpen(true)};
 const onFile=e=>{const f=e.target.files?.[0];if(f){setImage(f);setPreview(URL.createObjectURL(f))}};
 const save=async e=>{e.preventDefault();if(!editing&&!image){toast.error("Choose an image");return}const fd=new FormData();fd.append("is_active",String(active));fd.append("display_order",String(order||0));if(image)fd.append("image",image);try{const r=editing?await api.patch(`review-gallery/${editing.id}/`,fd):await api.post("review-gallery/",fd);setReviews(x=>editing?x.map(i=>i.id===editing.id?r.data:i):[r.data,...x]);setOpen(false);toast.success("Review image saved")}catch{toast.error("Unable to save image")}};
 const toggle=async r=>{const fd=new FormData();fd.append("is_active",String(!r.is_active));try{const res=await api.patch(`review-gallery/${r.id}/`,fd);setReviews(x=>x.map(i=>i.id===r.id?res.data:i))}catch{toast.error("Unable to change visibility")}};
 const remove=async r=>{if(!confirm("Delete this review image?"))return;try{await api.delete(`review-gallery/${r.id}/`);setReviews(x=>x.filter(i=>i.id!==r.id));toast.success("Review deleted")}catch{toast.error("Unable to delete review")}};
 return <DashboardLayout onLogout={onLogout} title="Review Gallery" subtitle="Manage customer feedback screenshots and photos." actionLabel="Add Review" onAction={showCreate}><div className="space-y-6">
 <div className="grid gap-4 sm:grid-cols-3"><Stat icon={Images} label="Total Reviews" value={reviews.length} tone="bg-violet-50 text-violet-600"/><Stat icon={Eye} label="Visible" value={reviews.filter(r=>r.is_active).length} tone="bg-emerald-50 text-emerald-600"/><Stat icon={EyeOff} label="Hidden" value={reviews.filter(r=>!r.is_active).length} tone="bg-orange-50 text-orange-600"/></div>
 <section className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="flex gap-2">{[["all","All"],["active","Visible"],["hidden","Hidden"]].map(([v,l])=><button key={v} onClick={()=>setFilter(v)} className={`rounded-lg px-4 py-2 text-sm ${filter===v?"bg-rose-500 text-white":"bg-gray-50 text-gray-600"}`}>{l}</button>)}</div><label className="relative"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by ID..." className="rounded-xl border py-2.5 pl-10 pr-3 text-sm outline-none"/></label></div>
 <div className="mt-5 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{loading?<p className="col-span-full py-16 text-center">Loading reviews…</p>:visible.length===0?<p className="col-span-full py-16 text-center text-gray-500">No review images found.</p>:visible.map(r=><article key={r.id} className="overflow-hidden rounded-2xl border border-gray-100 bg-white"><div className="aspect-[4/3] bg-gray-100"><img src={r.image_url||r.image} alt={`Review ${r.id}`} className="h-full w-full object-cover"/></div><div className="p-4"><div className="flex items-center justify-between"><div><p className="font-semibold">Review #{r.id}</p><p className="text-xs text-gray-400">Display order: {r.display_order||0}</p></div><span className={`rounded-full px-2.5 py-1 text-xs ${r.is_active?"bg-emerald-50 text-emerald-600":"bg-orange-50 text-orange-600"}`}>{r.is_active?"Visible":"Hidden"}</span></div><div className="mt-4 flex gap-2"><button onClick={()=>toggle(r)} className="flex-1 rounded-lg border py-2 text-xs">{r.is_active?"Hide":"Show"}</button><button onClick={()=>showEdit(r)} className="rounded-lg border p-2"><Pencil size={15}/></button><button onClick={()=>remove(r)} className="rounded-lg border border-rose-100 p-2 text-rose-500"><Trash2 size={15}/></button></div></div></article>)}</div></section>
 </div>{open&&<div className="fixed inset-0 z-[80] grid place-items-center bg-black/40 p-4"><form onSubmit={save} className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-3xl bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-bold">{editing?"Edit Review":"Add Review"}</h2><button type="button" onClick={()=>setOpen(false)}><X/></button></div><label className="mt-6 grid cursor-pointer place-items-center rounded-2xl border-2 border-dashed border-rose-200 p-5 text-center">{preview?<img src={preview} className="max-h-64 rounded-xl object-contain"/>:<><UploadCloud className="text-rose-500"/><span className="mt-2 text-sm">Choose review image</span></>}<input type="file" accept="image/*" onChange={onFile} className="hidden"/></label><div className="mt-5 grid grid-cols-2 gap-4"><label className="text-sm">Display order<input type="number" min="0" value={order} onChange={e=>setOrder(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="flex items-end gap-3 rounded-xl border p-3"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)} className="h-5 w-5 accent-rose-500"/><span className="text-sm">Visible on website</span></label></div><button className="mt-6 w-full rounded-xl bg-rose-500 py-3 font-semibold text-white">Save Review</button></form></div>}</DashboardLayout>}
