name: Lily Beauty Bar CI/CD 

# Trigger workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.3

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run migrations
      - name: Run Django Migrations
        run: |
          python manage.py migrate

      # Step 5: Run tests
      - name: Run Django Tests
        run: |
          python manage.py test

      # Step 6: Trigger Render deployment
      - name: Trigger Render Deploy
        run: |
          curl -X POST https://api.render.com/deploy/srv-d354ga0dl3ps738buvtg?key=LTuN42H29F0
